services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

      - MONGO_URI=mongodb://localhost:27017/stripe-app
      - JWT_SECRET=yourjwtsecret
      - STRIPE_SECRET_KEY=sk_test_51PcTLARsW7phZaeK6hCh0gv2DF91SeBfIgLe95y0C43LRc8BXWIpaQqN0t5QEQqKIkG7HZf3ANQ6tWhl3qLkZZ8X00B2486hLG
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
