services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/stripe-app
      - JWT_SECRET=456dedf6f09dbef082ee168d06060ed77570fbf39a09af4cf0625265c7ef53a1b80ff3a73d0b2530a916b672abd7e9d1bd31188b91e181e179c2e6c6216c88e8
      - STRIPE_SECRET_KEY=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
    depends_on:
      - mongo
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app-network

  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
