services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/stripe-app
      - JWT_SECRET=yourjwtsecret
      - STRIPE_SECRET_KEY=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
    depends_on:
      - mongo
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #     - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
